### PR TITLE
Buttons with text replaced with Image Buttons

### LINKED ISSUE #5: upgrade main screen buttons to Image Buttons
Currently the buttons have text on them (1-9 and 0 buttons and symbols). It would be great if they were upgrade to ImageButtons with drawables instead of text on the buttons.

### PR DESCRIPTION
**Pull request by unnikrishnan2002**
closes #5 

Image buttons added , content descriptions are also given for each button.

image   image

### CODE REVIEW

**Review by venusaim23 — CHANGES_REQUESTED** [review]
Hey @unnikrishnan2002 everything looks great except a few things.
- I just realized that misc.xml contains settings that are adjusted according to our local machine and these values might change from user to user. So, I'd want you to add ".idea/misc.xml" to .gitignore. There are some extra keys in that file too that have no purpose like line 29 and 34.
- I'd want to implement [binding](https://developer.android.com/topic/libraries/view-binding) in our application. This would save a lot of lines of code and we need not make objects for each element.
- Keep the button ids as add/subtract. Don't change the ids. Also, change the content descriptions as a command not an operation, like multiply instead of multiplication and divide instead of division. Also change the strings plus, minus to add and subtract.
- Add an attribute scaleType="fitCenter" for all the buttons. This would ensure that the button is responsive over all screen sizes. I'm not sure of the default value, so I included this attribute.
- Background Tint isn't necessary for ImageButton to maintain transparency. Remove it. I added the attribute to the buttons earlier because by default the buttons in material theme have a colored background.

**Comment by unnikrishnan2002** [comment]
Hey @venusaim23 I will apply those changes , but I would need a little time because I don't know much about binding so will have to understand it a bit .

Also I attached the background tint because there was a light greyish tone in the background by default so when adding the background tint it appeared as transparent. Please take this in consideration

**Comment by venusaim23** [comment]
> Hey @venusaim23 I will apply those changes , but I would need a little time because I don't know much about binding so will have to understand it a bit .
> 
> Also I attached the background tint because there was a light greyish tone in the background by default so when adding the background tint it appeared as transparent. Please take this in consideration

Alright no issues. It's not necessary to contribute to MainActivity.java for this issue. You can leave it as it was. But I won't stop you to from studying about it. Will consider backgroundTint. Submit the other changes and I'll merge.

**Comment by unnikrishnan2002** [comment]
Thank you so much, can I just do the suggested UI related changes only in this PR. And can you please put up an issue for the binding thing so that I can work on it seperately till then can you just accept those UI related changes. If that's fine for you??

**Comment by venusaim23** [comment]
> Thank you so much, can I just do the suggested UI related changes only in this PR. And can you please put up an issue for the binding thing so that I can work on it seperately till then can you just accept those UI related changes. If that's fine for you??

Well it's not a problem. There's a lot to work on in this project. You can just delete all that you added in MainActivity.java and submit with the other requested changes. That deals with the issue. Rest I'll work a bit on logic and push a few commits. You can refer to that to understand binding better.

**Comment by unnikrishnan2002** [comment]
> > Thank you so much, can I just do the suggested UI related changes only in this PR. And can you please put up an issue for the binding thing so that I can work on it seperately till then can you just accept those UI related changes. If that's fine for you??
> 
> Well it's not a problem. There's a lot to work on in this project. You can just delete all that you added in MainActivity.java and submit with the other requested changes. That deals with the issue. Rest I'll work a bit on logic and push a few commits. You can refer to that to understand binding better.

Okay then I will just do those changes . Thanks for being so supportive .

**Comment by unnikrishnan2002** [comment]
I have made a commit with the suggested changes . Also, no need to consider about the background Tint ,it is appearing fine , I guess it was because I had given some other attributes before adding the tint but actually removed those attributes. After that I didn't check that without the tint. It is now working perfectly fine

**Comment by venusaim23** [comment]
Hey @unnikrishnan2002 I'll do this one for you since it's taking long. Rest everything's fine. Thanks for contributing.

**Comment by unnikrishnan2002** [comment]
> Hey @unnikrishnan2002 I'll do this one for you since it's taking long. Rest everything's fine. Thanks for contributing.

thank you so much

**Pull request merged**
