### PR TITLE
Issuefixed

### PR DESCRIPTION
**Pull request by VedRatan**
updated the button as imageviewbutton and also used image resource on that button

### CODE REVIEW

**Comment by venusaim23** [comment]
looks great! One last thing, fetch the changes in your repo and I'll merge the PR.

**Comment by venusaim23** [comment]
I think your repository is missing the latest commits. I've made slight modifications to the code. Fetch those changes before I merge your PR.

image

**Comment by VedRatan** [comment]
done with the task

**Comment by venusaim23** [comment]
@VedRatan congrats for being the first contributor 🎉 to the repository

**Pull request merged**
